<?php

return [
    'eksalasiVia' => [
        'Telp' => 'Telp',
        'Telegram' => 'Telegram',
        'WA' => 'WA',
        'Grup internal' => 'Grup internal',
        'Grup Solver' => 'Grup Solver',
    ],
    'contact' => [
        'Contacted' => 'Contacted',
        'Rna' => 'Rna',
        'Busy' => 'Busy',
        'Rejected' => 'Rejected',
        'Mailbox' => 'Mailbox',
        'Rechedule' => 'Rechedule',
    ],
    'reasonnoODS' => [
        'PEOPLE - Menunggu Konfirmasi Dari Pelanggan' => 'PEOPLE - Menunggu Konfirmasi Dari Pelanggan',
        'PEOPLE - Pelanggan Belum Melunasi Tagihan' => 'PEOPLE - Pelanggan Belum Melunasi Tagihan',
        'PEOPLE - Pelanggan Belum Upload Berkas' => 'PEOPLE - Pelanggan Belum Upload Berkas',
        'PEOPLE - Pelanggan Reschedule' => 'PEOPLE - Pelanggan Reschedule',
        'PEOPLE - Pelanggan Sulit Dihubungi' => 'PEOPLE - Pelanggan Sulit Dihubungi',
        'PEOPLE - Pelanggan Tetap Ingin Di visit' => 'PEOPLE - Pelanggan Tetap Ingin Di visit',
        'PEOPLE - Pelanggan Tidak Ada Dilokasi' => 'PEOPLE - Pelanggan Tidak Ada Dilokasi',
        'PEOPLE - Teknisi Full Order' => 'PEOPLE - Teknisi Full Order',
        'PEOPLE - Unit Solver No Respon' => 'PEOPLE - Unit Solver No Respon',
        'PEOPLE - Mapping KIP Tidak Sesuai' => 'PEOPLE - Mapping KIP Tidak Sesuai',
        'PROSES - Status Order Tidak Sesuai' => 'PROSES - Status Order Tidak Sesuai',
        'PROSES - Workzone Kosong' => 'PROSES - Workzone Kosong',
        'PROSES - Ada Permintaan Berlangsung' => 'PROSES - Ada Permintaan Berlangsung',
        'PROSES - Alamat Tidak Sesuai' => 'PROSES - Alamat Tidak Sesuai',
        'PROSES - GAMAS' => 'PROSES - GAMAS',
        'PROSES - ODP Full' => 'PROSES - ODP Full',
        'PROSES - Mandeg UFO' => 'PROSES - Mandeg UFO',
        'PROSES - Mandeg IT' => 'PROSES - Mandeg IT',
        'TOOLS - Labor WO belum Completed' => 'TOOLS - Labor WO belum Completed',
        'TOOLS - UNSPEC' => 'TOOLS - UNSPEC',
        'TOOLS - Tidak Bisa Takeownership' => 'TOOLS - Tidak Bisa Takeownership',
    ],
    'responBE' => [
        'Balas chat & Memberi Update Progress' => 'Balas chat & Memberi Update Progress',
        'Hanya di Read saja' => 'Hanya di Read saja',
        'Membalas chat tapi lama (Lowrespon)' => 'Membalas chat tapi lama (Lowrespon)',
        'Hanya Membalas Chat (Fast Respon)' => 'Hanya Membalas Chat (Fast Respon)',
        'Menjawab Telp dan memberi Update' => 'Menjawab Telp dan memberi Update',
        'Respon Menolak Kordinasi' => 'Respon Menolak Kordinasi',
        'Tidak menerima koord C4' => 'Tidak menerima koord C4',
        'Tanpa Koordinasi' => 'Tanpa Koordinasi',
        'Tidak Membalas Chat' => 'Tidak Membalas Chat',
        'Tidak Menjawab Telp' => 'Tidak Menjawab Telp',
        'Menjawab Telp Saja' => 'Menjawab Telp Saja',
        'Membalas chat namun tidak memberi update progress' => 'Membalas chat namun tidak memberi update progress',
    ],
    'klasifikasi' => [
        'Technical' => 'Technical',
        'Non-Technical' => 'Non-Technical',
    ],
    'topic' => [
        'Internet Issue' => 'Internet Issue',
        'Phone Issue' => 'Phone Issue',
    ],
    'topicDetail' => [
        'Slow Connection' => 'Slow Connection',
        'No Connection' => 'No Connection',
    ],
    'noSC' => [
        'SC001' => 'SC001',
    ],
    'statusSC' => [
        'Open' => 'Open',
        'Closed' => 'Closed',
    ],
    'validateClose' => [
        'Yes' => 'Yes',
        'No' => 'No',
    ],
];
